# Generated by Django 4.1.5 on 2023-08-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
