# Generated by Django 4.1.5 on 2023-08-21 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_productunit_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwarranty',
            name='date_purchased',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productwarranty',
            name='warranty_duration',
            field=models.PositiveIntegerField(default=180),
        ),
    ]
