# Generated by Django 4.1.5 on 2023-05-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_margin',
            field=models.FloatField(default=0.25),
        ),
    ]
