# Generated by Django 4.1.5 on 2023-05-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_product_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.FloatField(default=0.0),
        ),
    ]
