# Generated by Django 4.1.5 on 2023-05-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='6 months', max_length=100)),
                ('date_purchased', models.DateTimeField(blank=True, null=True)),
                ('warranty_duration', models.IntegerField(default=180)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='money_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_serial',
            field=models.BooleanField(default=False, verbose_name='with serial?'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.productwarranty'),
        ),
    ]
