# Generated by Django 4.1.5 on 2023-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_productwarranty_orderitem_money_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
