# Generated by Django 4.1.5 on 2023-05-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_stocktransaction_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
