# Generated by Django 4.1.5 on 2023-05-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_category_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
    ]
